Assigment 4- DAV 5400

Problem1

In [7]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

#using numPy
print (np.intersect1d(a,b))

#without numPy
print (set(a).intersection(b))

[2 4]
{2, 4}


Problem 2

In [2]:
import numpy as np

#define the array dimensions
rows = 3
columns = 5
#define variable that will use as a counter and first attribute
counter = 1

#filling the array with zeros according to arrray size
a = np.zeros((columns,rows))

#allocate values in the array by using the counter
for j in range(rows):
    for i in range(columns):
        a[i][j] = counter
        counter += 1
print (a)

[[ 1.  6. 11.]
 [ 2.  7. 12.]
 [ 3.  8. 13.]
 [ 4.  9. 14.]
 [ 5. 10. 15.]]


Problem 3

In [6]:
import numpy as np

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

#for each value in array a append value if it's not in b array
a = [x for x in a if x not in b]
print (a)

[7, 15, 1, 8]


Problem 4

In [3]:
from random import randint
import numpy as np

#counter for number of cycels
recorded_days = 1
#counter for record no cycles days 
num_of_no_cycling_days = 0
#define array for all cycles record cummulative
recorded_miles_array = [0]
rand_flag = False

while recorded_days < 36:
    # 29h day if no 0 days yet
    # if 1 zero day then 31st
    # if 2 zero days then 33rd
    # if 3 zero days then 35th
    if (recorded_days == 29 and num_of_no_cycling_days == 0) or (
            recorded_days == 31 and num_of_no_cycling_days == 1) or (
            recorded_days == 33 and num_of_no_cycling_days == 2) or (
            recorded_days == 35 and num_of_no_cycling_days == 3):
        #append to recorded miles array if it's zero day
        recorded_miles_array.append(recorded_miles_array[recorded_days - 1])
        recorded_days += 1
        num_of_no_cycling_days += 1
    else:
        if rand_flag:
            last_record = int(recorded_miles_array[recorded_days - 1])
            record_to_add = randint(last_record, last_record + 62)
            recorded_miles_array.append(record_to_add)
            recorded_days += 1
            if record_to_add == last_record:
                num_of_no_cycling_days += 1
            continue

        print("enter the record the cumulative miles for day {0}".format(recorded_days))
        cumulative_miles = input()
        if cumulative_miles == 'rand':
            rand_flag = True
            continue
        try:
            val = int(cumulative_miles)
        except ValueError:
            print("That's not an int!")
            continue
        # if recorded_days > 0:
        if val >= recorded_miles_array[recorded_days - 1]:
            recorded_miles_array.append(val)
            if val == recorded_miles_array[recorded_days - 1]:
                num_of_no_cycling_days += 1
            recorded_days += 1
        else:
            print ("you cant input a record which is less than the previous day")

print ('record array: ', recorded_miles_array)
#using np to print the diff function to show total miles per each day
print ('miles rode per day array: ', np.diff(recorded_miles_array))



enter the record the cumulative miles for day 1
random
That's not an int!
enter the record the cumulative miles for day 1
rand
record array:  [0, 40, 75, 94, 136, 143, 181, 195, 203, 260, 271, 323, 348, 388, 441, 503, 524, 526, 550, 586, 586, 602, 637, 672, 707, 719, 755, 770, 772, 830, 849, 849, 854, 854, 893, 893]
miles rode per day array:  [40 35 19 42  7 38 14  8 57 11 52 25 40 53 62 21  2 24 36  0 16 35 35 35
 12 36 15  2 58 19  0  5  0 39  0]


Problem 5

In [13]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

print (nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

C:\Users\maaya\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [12]:
#define variavle for the first cell in the consumption column
maxConsumption = nyc_water[0][2]

#check along database 
for value in range(len(nyc_water)):
    # if 1512<=(next cell in column of consumption) assign to maxconsumption
      if maxConsumption <= nyc_water[value][2]:
    maxConsumption = nyc_water[value][2]
  
print("max consumption: ", maxConsumption)



max consumption:  1512.0


In [9]:

print(nyc_water[len(nyc_water) - 1][0] - nyc_water[0][0] +1 ,"calender years")

39.0 calender years


In [10]:
print(nyc_water[:,3])
print("mean: ", np.mean(nyc_water[:,3], axis = 0),"stdv: ", np.std(nyc_water[:,3], axis = 0))

[213. 213. 185. 194. 198. 203. 182. 185. 197. 202. 191. 194. 199. 184.
 182. 179. 174. 169. 155. 155. 156. 155. 148. 141. 136. 136. 141. 132.
 137. 135. 123. 127. 123. 121. 119. 118. 118. 117. 115.]
mean:  160.30769230769232 stdv:  31.51894330370624


In [11]:
pop_diff = np.diff(nyc_water[:,1])
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
