Assigment 4- DAV 5400

Problem1

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

#using numPy
print (np.intersect1d(a,b))

#without numPy
print (set(a).intersection(b))

Problem 2

In [8]:
import numpy as np

rows = 3
columns = 5
counter = 1

a = np.zeros((columns,rows))

for j in range(rows):
    for i in range(columns):
        a[i][j] = counter
        counter += 1
print (a)

[[ 1.  6. 11.]
 [ 2.  7. 12.]
 [ 3.  8. 13.]
 [ 4.  9. 14.]
 [ 5. 10. 15.]]


Problem 3

In [ ]:
import numpy as np

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

a = [x for x in a if x not in b]
print (a)

Problem 4

In [ ]:
from random import randint
import numpy as np

recorded_days = 1
num_of_no_cycling_days = 0
recorded_miles_array = [0]
rand_flag = False

while recorded_days < 36:
    # 29h day if no 0 days yet
    # if 1 zero day then 31st
    # if 2 zero days then 33rd
    # if 3 zero days then 35th
    if (recorded_days == 29 and num_of_no_cycling_days == 0) or (
            recorded_days == 31 and num_of_no_cycling_days == 1) or (
            recorded_days == 33 and num_of_no_cycling_days == 2) or (
            recorded_days == 35 and num_of_no_cycling_days == 3):
        recorded_miles_array.append(recorded_miles_array[recorded_days - 1])
        recorded_days += 1
        num_of_no_cycling_days += 1
    else:
        if rand_flag:
            last_record = int(recorded_miles_array[recorded_days - 1])
            record_to_add = randint(last_record, last_record + 62)
            recorded_miles_array.append(record_to_add)
            recorded_days += 1
            if record_to_add == last_record:
                num_of_no_cycling_days += 1
            continue

        print("enter the record the cumulative miles for day {0}".format(recorded_days))
        cumulative_miles = input()
        if cumulative_miles == 'rand':
            rand_flag = True
            continue
        try:
            val = int(cumulative_miles)
        except ValueError:
            print("That's not an int!")
            continue
        # if recorded_days > 0:
        if val >= recorded_miles_array[recorded_days - 1]:
            recorded_miles_array.append(val)
            if val == recorded_miles_array[recorded_days - 1]:
                num_of_no_cycling_days += 1
            recorded_days += 1
        else:
            print ("you cant input a record which is less than the previous day")

print ('record array: ', recorded_miles_array)
print ('miles rode per day array: ', np.diff(recorded_miles_array))



Problem 5

In [ ]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)



In [ ]:
maxConsumption = nyc_water[0][2]
for value in range(len(nyc_water)):
  if maxConsumption <= nyc_water[value][2]:
    maxConsumption = nyc_water[value][2]
  
print("max consumption: ", maxConsumption)



In [ ]:

print(nyc_water[len(nyc_water) - 1][0] - nyc_water[0][0] +1 ,"calender years")

In [ ]:
print(nyc_water[:,3])
print("mean: ", np.mean(nyc_water[:,3], axis = 0),"stdv: ", np.std(nyc_water[:,3], axis = 0))

In [ ]:
pop_diff = np.diff(nyc_water[:,1])
print(pop_diff)